### ISSUE TITLE
Plugin Working Fine in Dev and Staging but not in Production

### ISSUE THREAD

**Issue by NineBarCreative** [codemonauts/craft-instagram-feed#19] opened 2019-09-16 17:26 UTC
Hi there, I've just updated the Instagram Feed plugin to the latest version and am encountering an issue where the feed is working just fine on my development server and my staging server. But in production, the plugin isn't pulling in any images. There aren't any differences in the server environments from what I can tell and I've tried switching to guzzle but still nothing. Also allow_url_fopen is set to 1 on all 3 environments.

**Comment by kringkaste** [comment] 2019-09-17 08:28
Hi! Can you turn on the devMode on the production system and test it again? Then you will find debug output in the craft log file. Everything logged from codemonauts\instagramfeed will be helpful.

**Comment by NineBarCreative** [comment] 2019-09-17 13:52
So I turned on Dev mode on my production server and now the plugin is working lol. Anyhow, when looking through the web.log file on the production server, I see lots of these entries before dev mode was switched on:

2019-09-16 15:53:07 [-][-][-][error][codemonauts\instagramfeed\services\InstagramService::getInstagramAccountData] Instagram profile data could not be fetched. Maybe the site structure has changed.

**Comment by kringkaste** [comment] 2019-09-17 13:58
Ok, maybe you have cached an invalid response from Instagram. Did you clear the data cache at some point? To test if it is really working now: Switch devMode off, clear data cache from CP Tools Caching and reload page. If it's still working, you had a bad response in the cache. If it's not working, please turn dev Mode on, clear data cache, reload page, and look for the dump of the Instagram response in the web.log.

**Comment by NineBarCreative** [comment] 2019-09-17 14:16
So I turned off devMode, cleared the data cache and reloaded. The feed stopped working (but the feed was working after I turned production back on but before I cleared the cache). I then turned dev back on, cleared the data cache, reloaded and the feed is no longer working in dev mode. I looked through the web.log file and am not seeing any new references to any sort of error, just the same entries as I posted above from before going through this cycle this morning.

**Comment by kringkaste** [comment] 2019-09-17 14:29
With devMode on there must be a log entry (log level debug) with the complete Instagram response to the request we make. Either it looks like a complete HTML document or a JSON. This line(s) are the answer to the problem.

**Comment by NineBarCreative** [comment] 2019-09-17 14:52
Gotcha, well I looked back through and found this:
[instagram_feed_error_log.txt](https://github.com/codemonauts/craft-instagram-feed/files/3621972/instagram_feed_error_log.txt)

**Comment by kringkaste** [comment] 2019-09-17 15:06
Ok, can you tell me the Instagram account or hash tag you try to fetch?

**Comment by NineBarCreative** [comment] 2019-09-17 15:23
@forestrycamp

**Comment by kringkaste** [comment] 2019-09-17 16:08
Is the error log you provided the really the hole one? Because as I can see, there is a lot of information missing. The line beginning with

```
<script type="text/javascript">window._sharedData = {"config":{"csrf_token":"y7Ob8SmE4vLecZmkjNTTjVOk8SV8jL1l","viewer":null,"viewerId":null},"country_code":"US","language_code":"en","locale":"en_US","entry_data":{"LoginAndSignupPage":[{"c$
```

ends with this "$" and the rest of the JSON structure is missing. Can you check this?

**Comment by NineBarCreative** [comment] 2019-09-17 16:38
Hmm, weird, yea I definitely didn't catch that. This is the most recent block and I think it has everything:
[instagram_feed_error_log2.txt](https://github.com/codemonauts/craft-instagram-feed/files/3622513/instagram_feed_error_log2.txt)

**Comment by kringkaste** [comment] 2019-09-18 07:53
In this dump, there are other things missing. I'm not sure why the log does not have the complete page. This is strange. Did you install the plugin via composer? If so, can you switch to the dev-master version? I added a setting to write the hole response to a local file in the storage directory. Maybe this is better than fill the web.log. Please be sure to clear the data cache again and switch to devMode. And please send the log again. Thanks!

**Comment by NineBarCreative** [comment] 2019-09-18 13:50
Weird. I did install via composer so I'll give this a stab and upload the new log. Thank you!

**Comment by NineBarCreative** [comment] 2019-09-18 14:40
So I updated to the dev-master version and deployed to my production environment, cleared the cache and enabled devMode. I'm not seeing any new log files in storage but I am seeing a difference in my web.log which I've attached.
[instagram_feed_error_log3.txt](https://github.com/codemonauts/craft-instagram-feed/files/3626990/instagram_feed_error_log3.txt)

**Comment by fleaz** [comment] 2019-09-19 10:09
Hi @NineBarCreative 
thanks for the attached logfile. Apparantly Instagram is redirecting you to their login page instead of the profile page you requested, therefore our plugin can't parse any images.

We are quite sure this has to be some "problem" with your IP-Address/Geolocation in the eyes of Instagram and not with the plugin. We also tried to reproduce this behaviour with some of our servers in the US but all of them were working fine.

Do you have SSH access to your machine? Then you could try to run
```
curl https://www.instagram.com/forestrycamp -vL > /dev/null
```
in the terminal and show us the output. If this is also not working, Instagram doesn't likes your IP and we sadly can't do anything inside the plugin about it. If this works on your server, we probably do actually have a bug in the plugin because it does something strange.

Thanks for your patience and providing so much feedback to us :)

Best regards,
Felix

**Comment by NineBarCreative** [comment] 2019-09-19 15:44
Hi Felix,

Well I tried the curl command and the output on my dev server looks normal, it is pulling in the page. But on my production server, it is clearly redirecting to the login page. Do you have any suggestions on how I can get this working again or do I just need to look at a different feed implementation?

Thanks,
Nic

**Comment by fleaz** [comment] 2019-09-20 08:05
Hey,

when even curl isn't working then they really put your IP on some kind of blacklist :(

Other feed implementations will work, but only if you use one which uses a real IG account to login, and request the site while beeing logged in. This will probably work but is currently out of scope for this plugin.

Also bear in mind that using a real IG account in a server application will in bring along many other problems like suspended accounts if you e.g. use the account once on your phone and then on the server (two logins from different geographic locations).

Felix

**Comment by NineBarCreative** [comment] 2019-09-24 13:34
Thanks Felix, that makes sense. So the plugin is now suddenly working but intermittently? Since your response 4 days ago, I did no more commits or rebuilds on my production server. And Sunday AM, the feed started working (it included most recent images, etc). I did a rebuild Monday AM and it again stopped working, however a few hours later, it started pulling in images (again including most recent posts from that day, so I assume it isn't cache related). I don't know if this changes your thoughts on what is occurring but feel like it would be strange for Instagram to blacklist an IP, lift the ban, then reinstate it but only for a few hours.

**Comment by fleaz** [comment] 2019-09-25 09:51
This is indeed very strange behaviour and something we haven't seen so far. Sadly we are out of ideas how to proceed from here :(
And because we are fighting against the WAF/Bot detection/Firewall/... from Instagram in a semi-legal way, the support will probably also not be very helpful in this scenario

**Comment by NineBarCreative** [comment] 2019-09-26 15:34
Gotcha, well thank you for your help so far!

**Closed** 2019-09-27 13:44 UTC
Labels: support

**Comment by fleaz** [comment] 2020-04-06 14:51
Hey,

because multiple of our customers who use this plugin faced the same problem of beeing blacklisted by Instagram and therefore couldn't use our plugin, we started to implement a new feature which will circumvent this and use a proxy server to get the data.
If you still have this problem and wan't to give our plugin another chance, we would love to have you in our beta test for the next version.

Just write a mail to support@codemonauts.com and we will give you a beta key and all the details on how to use it :)

Best regards,
Felix
